theme: jekyll-theme-slate
title: "Charité Bioinformatics Tutorials"
baseurl: "/bioinformatics-tutorial"  # important for GitHub Pages under org/repo
url: "https://charite-infectious-diseases.github.io"

